### ISSUE TITLE
Hotkeys Changing Issue

### ISSUE THREAD

**Issue by mistermayomayo** [user-grinch/Cheat-Menu#100]
The script didn't record changes that was made to "Open/Close Cheat Menu" Hotkeys and "Open/Close Command Window" Hotkeys. It only records other hotkeys beside those two in the custom setting file.

I include log file and the setting file of my last run

<img width="960" alt="Gallery3" src="https://user-images.githubusercontent.com/96839507/236212360-933499ea-5764-420b-a0c0-1c1f6e1c4e20.png">
<img width="960" alt="Gallery4" src="https://user-images.githubusercontent.com/96839507/236212379-811f05e9-3816-4bb4-85f2-a74049ac1012.png">

[CheatMenuSA.txt](https://github.com/user-grinch/Cheat-Menu/files/11397738/CheatMenuSA.txt)
[CheatMenuSA.log](https://github.com/user-grinch/Cheat-Menu/files/11397739/CheatMenuSA.log)

**Comment by user-grinch** [comment]
Just checked it out. Seems to work fine in 3.6-beta
