### ISSUE TITLE
Menu text not loading

### ISSUE THREAD

**Issue by DarkTaker1990** [user-grinch/Cheat-Menu#102]
So I am attaching an image of what I see. I am using a v1.0 EXE for my Steam copy of the game. I put all the files where they should go but when I Left CTRL + M to open the menu, it looks like this. Not an issue in VC or SA. Just III for some reason. Any idea as to why?

I have the following mods installed:

SilentPatch
Widescreen Fix
SkyGFX
Your CheatMenu
And a couple CLEO mods.

I have all prerequisites installed as well.

This is really frustrating. I have been trying to fix it myself but to no avail.

Link to screenshot: https://pasteboard.co/XSPw45L3GTUE.jpg

**Comment by user-grinch** [comment]
Remove Globals.ini from asiloader

**Comment by aswertyStuff** [comment]
The real problem is, how do you do it? I mean...  I am using the ultimate asi loader by dll.  files, not the  folder version HLEP

**Comment by aswertyStuff** [comment]
my menu doesn't open anymore I have installed silent patch and draw dll but nothing

**Comment by user-grinch** [comment]
Join the discord server. I'll check there.

**Comment by user-grinch** [comment]
@aswertyStuff  @DarkTaker1990 
Can you guys try deleting scripts/globals.ini and check?

**Comment by DCaedus** [comment]
> @aswertyStuff @DarkTaker1990 Can you guys try deleting scripts/globals.ini and check?

deleting scripts/globals.ini did in fact fix the issue, making cheat menu go from no text to full text.

**Comment by user-grinch** [comment]
Aight, glad that helped. I'll update the installer soon to do it automatically next time.
