### ISSUE TITLE
No matter what I do, I can't navigate the menu

### ISSUE THREAD

**Issue by sohTeu** [user-grinch/Cheat-Menu#106]
AYO
Everytime I open it and click any of the buttons, **the mouse resets** for some reason (Yes i've followed the installations instructions)
Similar to:
#59 
#77

**Comment by user-grinch** [comment]
List your installed mods.

**Comment by sohTeu** [comment]
I'm new to modding this game so possibly I'm missing something, but
Here goes:
EXEE 1.0 US Hoodlum + 4 GB largeaddress patch
Silent's ASI Loader v1.3
CLEO v4.4.0 (no dev files)
CLEO+ v1.0.8 (no dev files)
ModLoader v0.3.7
SilentPatch v1.1 Build 32 (re-release)
Widescreen Fix by ThirteenAG 09/27/18
Widescreen Fix HOR + Support v1.0.2 (recompiled by ThirteenAG)
Windowed Mode v1.6
Framerate Vigilante 10/08/21
RunDLL32 Fix
NoDEP

**Comment by user-grinch** [comment]
Try removing wide-screen, windowed, no dep

**Comment by sohTeu** [comment]
It worked, Thanks a ton, this mod is top tier
