### ISSUE TITLE
(VC) Menu has no text similar to the GTA III error.

### ISSUE THREAD

**Issue by aswertyStuff** [user-grinch/Cheat-Menu#107]
![Grand Theft Auto Vice City Screenshot 2023 05 27 - 12 16 54 29](https://github.com/user-grinch/Cheat-Menu/assets/112781526/b726615e-7453-4d78-8c05-9ce7f68731f1)
   I have tried restarting the game and nothing happens  i am using vice city cleo btw,

**Comment by aswertyStuff** [comment]
Bruh, tell me to enable another asi loader or something

**Comment by user-grinch** [comment]
https://github.com/user-grinch/Cheat-Menu/issues/102#issuecomment-1546743690
