### ISSUE TITLE
Vehicle Extras

### ISSUE THREAD

**Issue by Pinkyo2386** [user-grinch/Cheat-Menu#110]
Maybe I've missed it in the menu but I'm kinda surprised theres no option to enable/disable vehicle extras, just because of the great vehicle customization there already is, I think it would be a great addition to the menu in my opinion.

**Comment by user-grinch** [comment]
Vehfuncs?

**Comment by Pinkyo2386** [comment]
> Vehfuncs?

no like regular gta sa cars can have extras like extra 1, 2 ,3 not sure how many is the limit but pieces of the car that will sometimes show up and sometimes not, this page explains https://gtaforums.com/topic/923709-sa-is-it-possible-to-make-vehicle-extras-only-appear-one-at-a-time-and-always-spawn-with-one-extras/

**Comment by Pinkyo2386** [comment]
visual spawner has the option to choose the extra you want the car to spawn with as well https://libertycity.net/files/gta-san-andreas/106991-visual-car-spawner-v3.0.html
