### ISSUE TITLE
[VC] Error 126 on Wine

### ISSUE THREAD

**Issue by strejda603** [user-grinch/Cheat-Menu#113]
Hello,

which exact DLLs does Cheat Menu depend on? No matter which version I install, everytime I got error 126 "Unable to load CheatMenuVC.asi"...

Got DirectX 9, Visual C++ Redistributable 2015-2022, Ultimate ASI Loader, Silent Patch and D3D8to9 wrapper installed, the game works fine, all mods installed work fine, even Modloader.. But Cheat Menu still fails to load... I even try to put it in the clean version of the game, but still got no luck..

If anyone got some suggestion, please let me know.

**Comment by user-grinch** [comment]
I haven't tried wine for quite some time. Having Dx9, Dx11, and VSRedist22 should be enough. Try going through dependency walker and check what you might be missing.
