### ISSUE TITLE
[SA]Error:d3d9.dll

### ISSUE THREAD

**Issue by Arash325** [user-grinch/Cheat-Menu#114]
I launched the game and i started a new game. The loading screen shows up but when it gets dark it shows the modloader error  with crash . It shows 4 problem and a crash log that says unhandled exception at 0x5E59BAC8 in d3d9.dll
I had installed all requirements .

**Comment by user-grinch** [comment]
Send screenshot of your game directory.

**Comment by Arash325** [comment]
Sorry for late 
I know there is some additionally files but i removed them and installed clean gta v1 again but still that issue . 
![20230730_220617](https://github.com/user-grinch/Cheat-Menu/assets/139973667/2517d846-5562-4ff9-a4e6-38a2be62352d)
![20230730_220603](https://github.com/user-grinch/Cheat-Menu/assets/139973667/b0b5678a-df94-4ef1-9666-1ab9cca1f9ee)
![20230730_220551](https://github.com/user-grinch/Cheat-Menu/assets/139973667/110681d3-89c8-447f-954a-e88771c17789)

**Comment by user-grinch** [comment]
This GTA SA is far from clean. There are tons of mods installed. Try on a fresh v1.0 game.
