### ISSUE TITLE
[SA] Increase Ped's Maximum Hp In The Ped Config

### ISSUE THREAD

**Issue by MonkeyDNARUT0** [user-grinch/Cheat-Menu#117]
NGL the only negative thing in this cheat menu which makes rzl trainer better than it is the ped's maximum hp limit its too low, im using saitama mod and i want a strong opponent but the maximum ped hp cannot pass 1000 hp while rzl trainer it can go 100000+ hp

**Comment by user-grinch** [comment]
Fixed in latest beta
