### ISSUE TITLE
Frame drop issue at startup

### ISSUE THREAD

**Issue by user-grinch** [user-grinch/Cheat-Menu#20]
Fix the fps drop issue with image loading.

More information would be helpful.

1. When the frame drop is actually occurring 
2. How many seconds it stays
3. Does it occur on each game start (new game)

**Comment by GamerTroxynYT** [comment]
1 basically at the startup of GTA Sa. You load a savegame and since the intialization of the Game's save starts dropping FPS.

2 For me, 1 minute

3 Yes.

Note:
Before the Nitro Bug: 8-12 FPS (according with Cheat Menu's FPS counter)
After the Nitro Fix: 12-20 FPS (the last time I've checked)

**Comment by user-grinch** [comment]
> Is this supposed to happen?
No idea how that happened.

**Comment by GamerTroxynYT** [comment]
> > Is this supposed to happen?
> 
> No idea how that happened.
> 
> Edit: Are you sure the issue occurs every time you launch the game? It seems to occur after every restart to me.

No, I said that happen at startup, that was i wanted to mean. Not in the launch game. Only when a savegame loaded ( startup )
