### ISSUE TITLE
Wrong Coordinates of Teleports! (Suggestion)

### ISSUE THREAD

**Issue by GamerTroxynYT** [user-grinch/Cheat-Menu#22]
I know Teleport is a EXCELLENT and ESSENTIAL ideia to ANY cheat menu, but the point is that Teleports doesn't works as should do. I'll give some examples that I've collected in this feature, places with a teleport that doesn't teleports you to a good position:
Sweet's Garage, Interior: Andromada , Interior: Sweet's House , Interior: Planning Dept , Interior: Liberty City Inside , Interior: Millie's House , Interior: Strip Club , Interior: Sex Shop , Interior: Crack Den , Interior: Millie's Room,but is the same teleport of Interior: Millie's House , Interior: 24/7 4 , Interior: Barbara's Room , Interior: Katie's Room and much more places are with problems in Teleport Coordinates...

Note: San Fierro: No Easter Eggs Up Here and San Fierro: Highest Building of San Fierro:  As you fall with CJ and with a certain direction that CJ is looking, you will fall from these places too. 
These Teleport Places I've said it's a part of the problematics places.
Just an enhancement in the coordinates can makes Teleports better.
Well, my third suggestion. That's it.

**Comment by user-grinch** [comment]
I've fixed this already after you told me on discord.  Just postponed the update a bit as I'm working on some other parts.

**Comment by GamerTroxynYT** [comment]
> I've fixed this already after you told me on discord. Just postponed the update a bit as I'm working on some other parts.

Oh! Okay, don't even worry about this. Work as you prefer!  :D
