### ISSUE TITLE
Rainbow Neons not working.

### ISSUE THREAD

**Issue by JorgeTebruski** [user-grinch/Cheat-Menu#37]
Change for fcommon.SingletonThread(module.RainbowNeons,"RainbowNeons") https://github.com/user-grinch/Cheat-Menu/blob/bdcb95932a9ea0b408132b3b1d779c38d921aa43/moonloader/lib/cheat-menu/modules/vehicle.lua#L1196

**Comment by user-grinch** [comment]
Thanks, should be fixed now.
