### ISSUE TITLE
Vehicle Camera instantly resets when you enter

### ISSUE THREAD

**Issue by danylopez123** [user-grinch/Cheat-Menu#38]
When you enter in any vehicle, the camera instantly resets to its original position when you enter in a vehicle.
This can be a problem for certain missions like in Reuniting The Families because as soon as you enter in the vehicle with the group when scaping the cops, the camera instantly resets and doesnt follow the cutscene cameras.

**Comment by user-grinch** [comment]
Fixed https://github.com/user-grinch/Cheat-Menu/commit/2474e5db7a4a8ac7e5b2dd06b5aa043954737ce4
