### ISSUE TITLE
Cheat Menu won't work with MSI Afterburner running in background

### ISSUE THREAD

**Issue by surrodox2001** [user-grinch/Cheat-Menu#43]
Game version: GTASA 1.00 hoodlum exe, v1 ipl and scm
Asi loader version: latest
Cheatmenu version: latest as of 2020-12-22 11:15 am UTC

Steps to reproduce:
1. Open MSI Afterburner in background.
2. Launch GTASA and load a save
3. Press keybind to open Cheatmenu, it doesn't open as expected. (no game crash happening)

This issue won't happen with MSI Afterburner closed.

**Comment by user-grinch** [comment]
![](https://cdn.discordapp.com/attachments/689515979847237695/790937182546296842/unknown.png)
Enable stealth mode
