### ISSUE TITLE
Incompatible mods - known fixes

### ISSUE THREAD

**Issue by user-grinch** [user-grinch/Cheat-Menu#48]
List of known mods that don't work fully or partially (with some options enabled).

## GTA SA
1. **ENB/ SA_DirectX 2.0** - disable **Effect/ Enable water or disable all overlay options in the cheatmenu**
2. **MSI Afterburner** - enable **Stealth mode** in rivatuner
3. **GTA Underground**
4. **Windowed Mode**
5. **Mixsets** - Disable the mouseFix option. Use SilentPatch.

## GTA III
1. SilentPatch **ddraw.dll** component. Just delete it for now.

**Comment by crz4all** [comment]
Games crash with Windowed Mod.
https://www.mixmods.com.br/2018/11/iiivcsa-windowed-mode.html

**Comment by user-grinch** [comment]
> Games crash with Windowed Mod.
> https://www.mixmods.com.br/2018/11/iiivcsa-windowed-mode.html

Which version? I just tried today, seems to work 🤔

**Comment by crz4all** [comment]
I'm use last version.  2.6.2
https://www.youtube.com/watch?v=Y_1JQXwdS5E

**Comment by thatazoreanguy** [comment]
Controller doesn't work with 2.7, however it does in 2.2

**Comment by user-grinch** [comment]
> The game doesn't recognize the controller with v2.7, however it works fine with v2.2

2.5x+ is totally different from previous versions. Sadly i don't own any controllers to properly implement controller support. If you got time on your hands and would like to help with testing join the discord server.

**Comment by user-grinch** [comment]
Added this in the [readme](https://github.com/user-grinch/Cheat-Menu/blob/rewrite/README.md)
