### ISSUE TITLE
Cheat Menu doesn't work when installing with Silent's ASI Loader

### ISSUE THREAD

**Issue by OscarX18** [user-grinch/Cheat-Menu#49]
**Describe the bug**
Tried to install cheat menu with Silent's ASI Loader but when I start the game nothing happens, so I went to scripts, opened cheatmenu.txt and it says this: "File doesn't exist ./CheatMenu/json/config.json", I checked that route and indeed the file doesn't exist
![image](https://user-images.githubusercontent.com/68449925/105538459-69e52300-5cc1-11eb-81eb-62e43dace62e.png)
![image](https://user-images.githubusercontent.com/68449925/105538575-9d27b200-5cc1-11eb-9f09-20b83bcbded6.png)
Then, I installed the mod with modloader and it worked perfectly

**Info**
Cheat Menu version (with build number): 2.5
Game Version (v1.0 required): 1.0 US
Windows Version (7/8/10): 10
Have you read the installation instructions? (Yes/No): Yes
Have you installed the menu using modloader? (Yes/No) (Provide log if installed): Yes 
[modloader.log](https://github.com/user-grinch/Cheat-Menu/files/5858281/modloader.log)

List of mods you have installed, ThirteenAG's Widescreen Fix, Unrated69's Cheat Menu, Silent's Patch
...

**Comment by user-grinch** [comment]
It's not a bug. It's just saying the config file doesn't exist (which shouldn't if you started the menu for the first time).

I'll change the debug message so it doesn't sound like a bug.

**Comment by user-grinch** [comment]
Nvm missed this part, 
`Tried to install cheat menu with Silent's ASI Loader but when I start the game nothing happens`
