### ISSUE TITLE
Crash on game load

### ISSUE THREAD

**Issue by crz4all** [user-grinch/Cheat-Menu#51]
I inform you that the "update checker" is causing the game to crash as soon as the save is loaded.
It seems to be random.

**Comment by user-grinch** [comment]
I'd need some more info to reproduce.
1. How you're certain it's the update checker & not anything else?
2. Are you trying on a fresh game? If not give that a try.
3. Any way to reproduce?

**Comment by crz4all** [comment]
It's very random, it usually happens when I do some mod editing, like Mixsets (.ini file) or Mobile Hud (.dat file).

In fresh game works fine.

In version 2.5, there was no updade check and it was never a problem.

Sorry for my bad English, I'm using Google Translate.

**Comment by user-grinch** [comment]
"It's very random, it usually happens when I do some mod editing, like Mixsets (.ini file) or Mobile Hud (.dat file)." 
I see. I'd guess something in MixSets probably messing with it. Try installing modloader & fastman92limit adjuster and check what those log says.

"In version 2.5, there was no updade check and it was never a problem."
There is a lot more under the hood changes to 2.6 than what was mentioned in the changelog. I'd be surprised if the updater was making the game crash.

"Sorry for my bad English, I'm using Google Translate"
No worries, seems okay to me

**Comment by crz4all** [comment]
An easy way to test is to remove or place any mod in the modloader folder, as soon as you do this, open the game.

**Comment by user-grinch** [comment]
It's never a good idea to load asi mods like that. I don't have any clue for me to believe the updater is causing it in the first place. If you could specify some certain mods which are causing it, I could check it out.

**Comment by crz4all** [comment]
See...
1 - https://www.youtube.com/watch?v=E86a7Xul5DU
2 - https://www.youtube.com/watch?v=VUZSNLaTqE8
3 - https://www.youtube.com/watch?v=DQcNeQap40g

**Comment by user-grinch** [comment]
> See...
> https://www.youtube.com/watch?v=a9DbSmhZX8w

The video confirms there's a crash but still no insight which mods might be causing it. Better if you contact me on discord. We can resolve it there.

**Comment by crz4all** [comment]
> > See...
> > https://www.youtube.com/watch?v=a9DbSmhZX8w
> 
> The video confirms there's a crash but still no insight which mods might be causing it. Better if you contact me on discord. We can resolve it there.

The same problem in using simple mods:
Silent's ASI Loader
CLEO 
CLEO+
ModLoader
SilentPatch
Widescreen Fix by ThirteenAG
Widescreen Fix HOR+ Support
Windowed Mode
Framerate Vigilante
RunDLL32 Fix
NoDEP

**Comment by user-grinch** [comment]
@crz4all Can you test the https://github.com/user-grinch/Cheat-Menu/releases/tag/2.6.2 and let me know?

**Comment by crz4all** [comment]
No crash so far, but the fast teleport has stopped working.

**Comment by user-grinch** [comment]
hmm, just tried it out tho, seems to work fine. Can you check if your hotkeys are set up properly? 
Anyway open another issue if it still persists.
