### ISSUE TITLE
Cannot open cheat menu

### ISSUE THREAD

**Issue by JULI4N0** [user-grinch/Cheat-Menu#52]
**Describe the bug**
A clear and concise description of what the bug is & steps to reproduce it. Screenshots or videos are helpful.

**Info**
Cheat Menu version (with build number):
Game Version (v1.0 required): 1
Windows Version (7/8/10): 10
Have you read the installation instructions? (Yes/No): yes
Have you installed the menu using modloader? (Yes/No) (Provide log if installed):  no 
List of mods you have installed,
...
The asi loader and the other asi thing that u said

**Comment by user-grinch** [comment]
Fill up the form properly. 
"A clear and concise description of what the bug is & steps to reproduce it. Screenshots or videos are helpful."
"Cheat Menu version (with build number):"

**Comment by JULI4N0** [comment]
![image](https://user-images.githubusercontent.com/42938517/115123132-91dbde00-9fb3-11eb-8bbb-ed8096af8a17.png)

when i press ctrl+m the menu doesnt pop up. i have v1.0.0 of gta sa and i used this version: 2.6.2

**Comment by JorgeTebruski** [comment]
You did not compile the project.

You have 3 options:

1 - Following the steps in the readme to compile

Building

You'll need to install Visual Studio 2019 (v142), DirectX9 SDK & Plugin SDK.

2 - Downloading the binaries at https://github.com/user-grinch/Cheat-Menu/releases

3 - Download beta binaries on Discord https://discord.gg/ZzW7kmf
