### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by PatricioCabrera** [user-grinch/Cheat-Menu#53]
I was using latest version normally, just with 2 random crashes on startup. Until it crashed because of teleporting too fast.
Now it always crashes on startup.
Previous version loads fine (but I can't use it).
[fastman92limitAdjuster.log](https://github.com/user-grinch/Cheat-Menu/files/6412399/fastman92limitAdjuster.log)

**Comment by user-grinch** [comment]
Try deleting the config.json file and check.
