### ISSUE TITLE
Unable to launch the game with CheatMenu

### ISSUE THREAD

**Issue by arwent** [user-grinch/Cheat-Menu#54]
**Describe the bug**
When starting the game, it crash instantly.

**Info**
Cheat Menu version (with build number): 2.6.2
Game Version (v1.0 required): 1.0
Windows Version (7/8/10): 10 20H4 19042.985
Have you read the installation instructions? (Yes/No): Yes
Have you installed the menu using modloader? (Yes/No) (Provide log if installed): No
List of mods you have installed,
- SA SilentPatch
- CheatMenu

![crashsa1](https://user-images.githubusercontent.com/45935408/119223546-655b3a80-bafa-11eb-838f-b4dfd9c4b305.png)

**Comment by user-grinch** [comment]
Reinstall the menu.

**Comment by arwent** [comment]
Already tried it using .7z from Discord and latest from Github.

**Comment by user-grinch** [comment]
> Already tried it using .7z from Discord and latest from Github.

Show me a screenshot of where tou put the menu.

**Comment by arwent** [comment]
![crashsa2](https://user-images.githubusercontent.com/45935408/119223757-6fca0400-bafb-11eb-8e4e-41843823130d.png)

Here ya go,
I've tried the version 2.5, the menu is working fine.

**Comment by user-grinch** [comment]
> ![crashsa2](https://user-images.githubusercontent.com/45935408/119223757-6fca0400-bafb-11eb-8e4e-41843823130d.png)
> 
> Here ya go,
> I've tried the version 2.5, the menu is working fine.
> I'll try to use the 2.5 config.json with 2.6.2 one.
> EDIT: Mhm, seems 2.5 does not create config.json or am I blind?

Can you ensure if all the json files are there? ( CheatMenu/json/*.json)

**Comment by arwent** [comment]
Yup, all seems to be here. (from 2.6.2)
![crashsa4](https://user-images.githubusercontent.com/45935408/119223942-64c3a380-bafc-11eb-86cc-6c5152fc0653.png)

**Comment by user-grinch** [comment]
That's strange. Have you tried putting them into the root game directory? If still doesn't work, join the discord server we can continue there.

**Comment by arwent** [comment]
Oh, seems to be working when putting it in the root game folder ! Thanks !

**Comment by user-grinch** [comment]
> Oh, seems to be working when putting it in the root game folder ! Thanks !

Aight, nice.
