### ISSUE TITLE
Crashes just after the intro video

### ISSUE THREAD

**Issue by Ninkyo** [user-grinch/Cheat-Menu#55]
**Describe the bug**
Run exe and crashes just after the intro video, Was working fine before I installed another car mod using modloader, so I went through all my stuff removing everything only to find the culprit is the Cheat Menu. So I removed it and I've had no issues, tried to reinstall it and I still have the same issue, so I have no idea what it broke but it broke something and whenever its there the game crashes. 

**Info**
Cheat Menu version (with build number): Latest
Game Version (v1.0 required): v.1.0
Windows Version (7/8/10): 10
Have you read the installation instructions? (Yes/No): Yes
Have you installed the menu using modloader? (Yes/No) (Provide log if installed): No, That's possible??

List of mods you have installed,
Basic ENB(Tried without)
Modloader(Tried without)
Cleo(Tried without)
I removed every ASI and DLL added, and the menu still crashes it.

**Comment by user-grinch** [comment]
I'll need some screenshots of where you installed it and your game directory. Also, try doing a clean install ( Delete both the CheatMenu.asi & cheatmenu folder)

**Comment by Ninkyo** [comment]
.
