### ISSUE TITLE
VC Version not opening

### ISSUE THREAD

**Issue by Nullzerep468** [user-grinch/Cheat-Menu#60]
Cheat Menu 3.0 not opening on vice city and i have installed all the prerequisites and no globals.ini folder was created. game version is 1.0 and no matter what it still will not open. i have reinstalled numerous times but nothing has changed what did i do wrong

**Comment by user-grinch** [comment]
Send screenshot of your game directory

**Comment by Nullzerep468** [comment]
![Grand Theft Auto Vice City 12_26_2021 3_30_07 PM](https://user-images.githubusercontent.com/56565080/147419356-5306e865-6559-493e-a198-f02ca44dcf08.png)

**Comment by user-grinch** [comment]
Everything seems right. The menu was also loaded ( since the log is there ). Maybe something went wrong elsewhere. Join the discord server. Can help faster there.

**Comment by Nullzerep468** [comment]
got it
