### ISSUE TITLE
change hotkeys

### ISSUE THREAD

**Issue by SapityNapity** [user-grinch/Cheat-Menu#67]
how do you change hotkeys i left click the key but it just says "clear" and when i press the key i want it to set to nothing happens

**Comment by user-grinch** [comment]
Maybe show a short clip?

**Comment by SapityNapity** [comment]
> Maybe show a short clip?

nvm it works now it has way less features than rzl trainer but i want this one to have the same features as rzl trainer,
love this one but it lacks features

**Comment by user-grinch** [comment]
> > Maybe show a short clip?
> 
> nvm it works now it has way less features than rzl trainer but i want this one to have the same features as rzl trainer, love this one but it lacks features

If you want features, make another issue with your details.
