### ISSUE TITLE
Tune handling cars issue

### ISSUE THREAD

**Issue by Rapaduraw** [user-grinch/Cheat-Menu#85]
After update 3.5 and 3.51, the handling options are broken, for example: the default value of engine acceleration of a turismo is 1897332.0, if i try to change it it will default to 49.000 and i can´t change that value. Also, #Vehicle.LowerKimit crashes the game when i click on it.

**Comment by user-grinch** [comment]
Should be fixed in newer versions

**Comment by Rapaduraw** [comment]
ok
