### ISSUE TITLE
Using the supported language but still appears ???

### ISSUE THREAD

**Issue by Ningning1046** [user-grinch/Cheat-Menu#86]
![image](https://user-images.githubusercontent.com/72305399/212045219-e32b204b-5eff-41d6-b2d1-c433273c270d.png)

**Comment by user-grinch** [comment]
You need to install the language support package for Chinese.
![image](https://user-images.githubusercontent.com/29150216/212508484-06040e3f-9033-47d7-9301-2a955e71c046.png)
![image](https://user-images.githubusercontent.com/29150216/212508557-068019de-e4b3-4d27-b4e7-358bc7730527.png)
