### ISSUE TITLE
Screenshot doesn't work

### ISSUE THREAD

**Issue by Viniciaao** [user-grinch/Cheat-Menu#87]
Screenshot doesn't work, I'm already on the latest version(v3.52 (Jan 8 2023))
Log do CheatMenu
[CheatMenuSA.log](https://github.com/user-grinch/Cheat-Menu/files/10419149/CheatMenuSA.log)

**Comment by user-grinch** [comment]
Enable "Store Gallery Photos" in game settings.
![image](https://user-images.githubusercontent.com/29150216/212509855-54e00f5a-c7db-470b-89cc-ad4e0bbb4696.png)

**Comment by Viniciaao** [comment]
I'm not on PC at the moment (01/15 12:04) but I find I always leave this on (if I have it off I'll be very surprised) I'll leave correct feedback later

**Comment by Viniciaao** [comment]
It's already activated, there really is an error in the cheat menu

**Comment by Viniciaao** [comment]
yes, the pictures taken with the game camera are saved, I use PortableGTA and Mixsets to increase the resolution

**Comment by user-grinch** [comment]
> yes, the pictures taken with the game camera are saved, I use PortableGTA and Mixsets to increase the resolution

That's quite strange. Game camera works but this doesn't 🤔. How about without PortableGTA? Kindly try without other mods that might interfere and lemme know.

**Comment by Viniciaao** [comment]
ok i will try that

Em sex., 20 de jan. de 2023 1:50 PM, Grinch_ ***@***.***>
escreveu:

**Comment by Viniciaao** [comment]
it seems that it was incompatibility with portableGTA if you can fix that it would be good since portableGTA is a very important mod for anyone who has more than one GTA
