### ISSUE TITLE
When I spawn a car it always appears tuned

### ISSUE THREAD

**Issue by DanThe12** [user-grinch/Cheat-Menu#89]
Hello, I installed the new version of the mod, but it happens that every time I spawn a vehicle, it always spawns tuned, and that causes cars that I replace that don't support tunings to crash the game. Is there a way to disable this?

**Comment by user-grinch** [comment]
> Hello, I installed the new version of the mod, but it happens that every time I spawn a vehicle, it always spawns tuned, and that causes cars that I replace that don't support tunings to crash the game. Is there a way to disable this?
Right click on one of those vehicle images.  A option should appear to disable tune spawn.
