### ISSUE TITLE
Ginput Issue

### ISSUE THREAD

**Issue by Ruethy** [user-grinch/Cheat-Menu#90]
When playing with a controller via steam deck or PC, if you hold X on Xbox style controller a grey window will pop up for as long as you hold the button. If you close the menu and Hold X again the issue persist till tabbed out then it foxes itself until you open the menu again.

Would it be plausible to disable controller input just like add it as a button? 

![image](https://user-images.githubusercontent.com/69994072/213921334-034ad111-9f3f-4d30-bf10-dc752321a059.png)

**Comment by user-grinch** [comment]
Was it resolved with the beta? @Ruethy
