### ISSUE TITLE
[SA] Issue with regen delay

### ISSUE THREAD

**Issue by Frouk3** [user-grinch/Cheat-Menu#94]
when player takes damage it should regenerate without delay of 5 seconds(after damage wasn't taken for 5 seconds, it still waits 5 seconds to regen)
Add infinite ammo on missions

**Comment by user-grinch** [comment]
@Frouk3 Can you explain it again? I'm failing to understand what you meant.

**Comment by Frouk3** [comment]
uhh, i think it was delayed because i only saw the health adding on hud, and i didn't look into actual value of health

**Comment by user-grinch** [comment]
I just checked it out. The feature is working as expected. The 5 second delay is by design.
