### ISSUE TITLE
dude,where is my parachute??

### ISSUE THREAD

**Issue by MohamedSaif44** [user-grinch/Cheat-Menu#96]
**Awesome mod,thanks man,makes replaying much easier**<br/>
in my previous version(3.2 i think) when i got in a plane i got automatic parachute,which make moving around fun,and there was no need for teleportation.

**Comment by user-grinch** [comment]
Can you elaborate?

**Comment by Frouk3** [comment]
> **Awesome mod,thanks man,makes replaying much easier** in my previous version(3.2 i think) when i got in a plane i got automatic parachute,which make moving around fun,and there was no need for teleportation.

Game is just automatically gives it to you when you reach required pilot skill
